### ISSUE TITLE
Punishments not showing up in discord when executed.

### ISSUE THREAD

**Issue by PofileMaine** [Spicord/BanAnnouncer#102]
I am using LiteBans for my punishments plugin and have fully set up Spicord and BanAnnouncer. I notice I get this error message when I issue punishments from Litebans. I think this is a BanAnnouncer issue as Litebans is working fine, but I could be wrong.

[20:28:28 WARN]: java.sql.SQLException: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.
[20:28:28 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
[20:28:28 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[20:28:28 WARN]:        at com.mysql.cj.jdbc.result.ResultSetImpl.first(ResultSetImpl.java:617)
[20:28:28 WARN]:        at LiteBans.jar//litebans.dH.first(dH.java)
[20:28:28 WARN]:        at BanAnnouncer_2.6.3 (1).jar//eu.mcdb.ban_announcer.listener.LiteBansListener.getPlayerName(LiteBansListener.java:119)
[20:28:28 WARN]:        at BanAnnouncer_2.6.3 (1).jar//eu.mcdb.ban_announcer.listener.LiteBansListener.handleEntry(LiteBansListener.java:81)
[20:28:28 WARN]:        at BanAnnouncer_2.6.3 (1).jar//eu.mcdb.ban_announcer.listener.LiteBansListener$InternalListener.entryAdded(LiteBansListener.java:138)
[20:28:28 WARN]:        at LiteBans.jar//litebans.g1.a(g1.java:13)
[20:28:28 WARN]:        at LiteBans.jar//litebans.cs.run(cs.java:57)
[20:28:28 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:28:28 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:28:28 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[20:28:28 ERROR]: [LiteBans] An uncaught exception was thrown by a LiteBans API event listener.
[20:28:28 ERROR]: [LiteBans] This is likely a bug in a plugin which is using the LiteBans API.
[20:28:28 WARN]: java.lang.IllegalStateException: Couldn't fetch player name from UUID 'cb77ca74-f83d-424c-ac14-d8f7348d5a74'. The message was not sent.
[20:28:28 WARN]:        at BanAnnouncer_2.6.3 (1).jar//eu.mcdb.ban_announcer.listener.LiteBansListener.handleEntry(LiteBansListener.java:84)
[20:28:28 WARN]:        at BanAnnouncer_2.6.3 (1).jar//eu.mcdb.ban_announcer.listener.LiteBansListener$InternalListener.entryAdded(LiteBansListener.java:138)
[20:28:28 WARN]:        at LiteBans.jar//litebans.g1.a(g1.java:13)
[20:28:28 WARN]:        at LiteBans.jar//litebans.cs.run(cs.java:57)
[20:28:28 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:28:28 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:28:28 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by anvorgesa** [comment]
This was already solved. Read the issue history before creating new ones.
