### ISSUE TITLE
Bans from console throw errors

### ISSUE THREAD

**Issue by Impactic48** [Spicord/BanAnnouncer#105]
How to replicate: 
Put LiteBans, Spicord, and BanAnnouncer on Velocity.
Ban a player through console on a backend server
Throws the error below on console of backend server

Error:
`tempban skinheads 5s -s
[19:00:30 ERROR]: [LiteBans] An uncaught exception was thrown by a LiteBans API event listener.
[19:00:30 ERROR]: [LiteBans] This is likely a bug in a plugin which is using the LiteBans API.
[19:00:30 WARN]: java.lang.NullPointerException: Cannot invoke "org.spicord.bot.DiscordBot.getJda()" because "this.bot" is null
[19:00:30 WARN]:        at BanAnnouncer_2.5.3.jar//eu.mcdb.ban_announcer.BanAnnouncer.sendDiscordMessage(BanAnnouncer.java:111)
[19:00:30 WARN]:        at BanAnnouncer_2.5.3.jar//eu.mcdb.ban_announcer.BanAnnouncer.handlePunishmentAction(BanAnnouncer.java:102)
[19:00:30 WARN]:        at BanAnnouncer_2.5.3.jar//eu.mcdb.ban_announcer.PunishmentListener.handlePunishment(PunishmentListener.java:12)
[19:00:30 WARN]:        at BanAnnouncer_2.5.3.jar//eu.mcdb.ban_announcer.listener.LiteBansListener.handleEntry(LiteBansListener.java:108)
[19:00:30 WARN]:        at BanAnnouncer_2.5.3.jar//eu.mcdb.ban_announcer.listener.LiteBansListener$InternalListener.entryAdded(LiteBansListener.java:138)
[19:00:30 WARN]:        at LiteBans(1)(1)(1).jar//litebans.g1.a(g1.java:13)
[19:00:30 WARN]:        at LiteBans(1)(1)(1).jar//litebans.cs.run(cs.java:57)
[19:00:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[19:00:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[19:00:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by anvorgesa** [comment]
You are using a very old BanAnnouncer version, update the plugins and if you get an error then report it, but do not report errors when using old plugin versions, as they could have already been fixed in newer ones.
