### ISSUE TITLE
Announce error

### ISSUE THREAD

**Issue by thiagogebrimm** [Spicord/BanAnnouncer#107]
```
[11:35:36 ERROR]: [LiteBans] An uncaught exception was thrown by a LiteBans API event listener.
[11:35:36 WARN]: java.lang.LinkageError: loader constraint violation: loader 'BanAnnouncer_2.6.4.jar' @3eb669ed wants to load interface net.dv8tion.jda.api.JDA. A different interface with the same name was previously loaded by 'Spicord_4.2.4.jar' @385da86f. (net.dv8tion.jda.api.JDA is in unnamed module of loader 'Spicord_4.2.4.jar' @385da86f, parent loader java.net.URLClassLoader @3f8f9dd6)
[11:35:36 WARN]:        at BanAnnouncer_2.6.4.jar//eu.mcdb.ban_announcer.BanAnnouncer.sendDiscordMessage(BanAnnouncer.java:136)
[11:35:36 WARN]:        at BanAnnouncer_2.6.4.jar//eu.mcdb.ban_announcer.BanAnnouncer.handlePunishmentAction(BanAnnouncer.java:118)
[11:35:36 WARN]:        at BanAnnouncer_2.6.4.jar//eu.mcdb.ban_announcer.PunishmentListener.handlePunishment(PunishmentListener.java:12)
[11:35:36 WARN]:        at BanAnnouncer_2.6.4.jar//eu.mcdb.ban_announcer.listener.LiteBansListener.handleEntry(LiteBansListener.java:113)
[11:35:36 WARN]:        at BanAnnouncer_2.6.4.jar//eu.mcdb.ban_announcer.listener.LiteBansListener$InternalListener.entryAdded(LiteBansListener.java:143)
[11:35:36 WARN]:        at LiteBans.jar//litebans.j.b(j.java:13)
[11:35:36 WARN]:        at LiteBans.jar//litebans.B.run(B.java:57)
[11:35:36 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:35:36 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:35:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by anvorgesa** [comment]
Hi, I have not been notified by GitHub of this issue you created, I discovered it now because I have manually entered to the issues section, sorry for the delayed response.

Please send the full server startup log
