### ISSUE TITLE
Exception encountered when loading plugin: BanAnnouncer

### ISSUE THREAD

**Issue by Dusten9752** [Spicord/BanAnnouncer#114]
Whenever I start my server I get this error as the plugin loads before LiteBans does.

[11:58:27 WARN]: Exception encountered when loading plugin: BanAnnouncer
litebans.api.exception.MissingImplementationException: LiteBans API implementation is not available! This means that LiteBans is not installed on this server or it hasn't been loaded yet.
        at litebans.api.Events.get(Events.java:23) ~[?:?]
        at me.tini.announcer.listener.LiteBansListener.<init>(LiteBansListener.java:41) ~[?:?]
        at me.tini.announcer.bungee.BanAnnouncerBungee.lambda$onSpicordLoad$1(BanAnnouncerBungee.java:64) ~[?:?]
        at me.tini.announcer.PunishmentListeners$PunishmentManagerInfo.newInstance(PunishmentListeners.java:125) ~[?:?]
        at me.tini.announcer.PunishmentListeners.startPunishListener(PunishmentListeners.java:50) ~[?:?]
        at me.tini.announcer.bungee.BanAnnouncerBungee.onSpicordLoad(BanAnnouncerBungee.java:76) ~[?:?]
        at org.spicord.SpicordLoader.addStartupListener(SpicordLoader.java:124) ~[?:?]
        at me.tini.announcer.bungee.BanAnnouncerBungee.onEnable(BanAnnouncerBungee.java:44) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:357) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:a6203d6:unknown]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:311) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:a6203d6:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:52) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:a6203d6:unknown]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:a6203d6:unknown]

**Comment by anvorgesa** [comment]
That's strange because LiteBans is already a softdepend in BanAnnouncer.
Please send the server startup log so I can look into it.

**Comment by Dusten9752** [comment]
https://pastebin.com/HDtK8gaj

**Comment by Dusten9752** [comment]
https://pastebin.com/B3eZRqmS

**Comment by anvorgesa** [comment]
Sorry for the late response, I'm not very active on GitHub.

You can fix this by modifying the load delay of Spicord, set it to 15 instead of 10, here's the line: 
https://github.com/Spicord/Spicord/blob/v5/common/src/main/resources/config.toml#L13

**Comment by Dusten9752** [comment]
Thanks this worked!
