### ISSUE TITLE
Error By The Plugin

### ISSUE THREAD

**Issue by GALAXY30000** [Spicord/BanAnnouncer#117]
[20:51:05 ERROR]: [LiteBans] An uncaught exception was thrown by a LiteBans API event listener.
[20:51:05 ERROR]: [LiteBans] This is likely a bug in a plugin which is using the LiteBans API.
[20:51:05 WARN]: java.lang.IllegalArgumentException: URL must be a valid http(s) or attachment url.
[20:51:05 WARN]:        at Spicord_5.3.1.jar//net.dv8tion.jda.internal.utils.Checks.check(Checks.java:62)
[20:51:05 WARN]:        at Spicord_5.3.1.jar//net.dv8tion.jda.api.EmbedBuilder.urlCheck(EmbedBuilder.java:907)
[20:51:05 WARN]:        at Spicord_5.3.1.jar//net.dv8tion.jda.api.EmbedBuilder.setFooter(EmbedBuilder.java:798)
[20:51:05 WARN]:        at Spicord_5.3.1.jar//org.spicord.embed.Embed.toJdaEmbed(Embed.java:396)
[20:51:05 WARN]:        at Spicord_5.3.1.jar//org.spicord.embed.EmbedSender.prepare(EmbedSender.java:29)
[20:51:05 WARN]:        at BanAnnouncer_2.8.2.jar//me.tini.announcer.BanAnnouncer.sendDiscordMessage(BanAnnouncer.java:161)
[20:51:05 WARN]:        at BanAnnouncer_2.8.2.jar//me.tini.announcer.BanAnnouncer.handlePunishmentAction(BanAnnouncer.java:133)
[20:51:05 WARN]:        at BanAnnouncer_2.8.2.jar//me.tini.announcer.PunishmentListener.handlePunishment(PunishmentListener.java:12)
[20:51:05 WARN]:        at BanAnnouncer_2.8.2.jar//me.tini.announcer.listener.LiteBansListener.handleEntry(LiteBansListener.java:125)
[20:51:05 WARN]:        at BanAnnouncer_2.8.2.jar//me.tini.announcer.listener.LiteBansListener$InternalListener.entryAdded(LiteBansListener.java:155)
[20:51:05 WARN]:        at LiteBans.jar//litebans.jY.b(jY.java:13)
[20:51:05 WARN]:        at LiteBans.jar//litebans.dT.run(dT.java:57)
[20:51:05 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:51:05 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:51:05 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[20:51:05 INFO]: Console banned Gakay for 'The Ban Hammer has spoken!'

**Comment by anvorgesa** [comment]
You have an embed file that has an invalid url in the footer, it may be due to a missing protocol (`http://` or `https://`).

**Comment by GALAXY30000** [comment]
{
  "embed": {
    "title": "Ban ",
    "description": "
# Player  → `%player%` 
# Banned By → `%staff%`
 # Reason For Ban → `%reason%`",
    "color": 14169911,
    "footer": {
      "icon_url": "https://cdn.discordapp.com/attachments/1092732183946469396/1213208528144044092/pvp_verse.jpg ex=65f4a37d&is=65e22e7d&hm=e4be1e2981c4659f04cfde2e4973aba639896fae1641f8396babbae8ac36fffb&",
      "text": "Published By PvP Verse"
    }
  }
}
all embeds are same

**Comment by anvorgesa** [comment]
And there's an space after the .jpg, that makes the url invalid.
