### ISSUE TITLE
 I get errors when trying to transmit sanctions events with LiteBans

### ISSUE THREAD

**Issue by ElkinSantiana** [Spicord/BanAnnouncer#33]
[17:04:53 WARN]: java.lang.IllegalStateException: Database connection not available
[17:04:53 WARN]:        at litebans.d6.prepareStatement(d6.java:24)
[17:04:53 WARN]:        at eu.mcdb.ban_announcer.listener.LiteBans.getName(LiteBans.java:48)
[17:04:53 WARN]:        at eu.mcdb.ban_announcer.listener.LiteBans.access$200(LiteBans.java:31)
[17:04:53 WARN]:        at eu.mcdb.ban_announcer.listener.LiteBans$LiteBansListener.handleEntry(LiteBans.java:111)
[17:04:53 WARN]:        at eu.mcdb.ban_announcer.listener.LiteBans$LiteBansListener.entryAdded(LiteBans.java:72)
[17:04:53 WARN]:        at litebans.bB.run(bB.java:8)
[17:04:53 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[17:04:53 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[17:04:53 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by OopsieWoopsie** [comment]
Hi, you will need to report this issue to the LiteBans owner, as this is not a BanAnnouncer issue.
