### ISSUE TITLE
The warns give an error with LiteBans

### ISSUE THREAD

**Issue by cferreras** [Spicord/BanAnnouncer#34]
`[23:34:32 ERROR] [LiteBans]: An uncaught exception was thrown by a LiteBans API event listener.
[23:34:32 ERROR] [LiteBans]: This is likely a bug in a plugin which is using the LiteBans API.
[23:34:32 ERROR]: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 142 path $.embed.description
[23:34:32 ERROR]:       at com.google.gson.Gson.fromJson(Gson.java:902)
[23:34:32 ERROR]:       at com.google.gson.Gson.fromJson(Gson.java:852)
[23:34:32 ERROR]:       at com.google.gson.Gson.fromJson(Gson.java:801)
[23:34:32 ERROR]:       at com.google.gson.Gson.fromJson(Gson.java:773)
[23:34:32 ERROR]:       at eu.mcdb.spicord.embed.EmbedParser.parse(EmbedParser.java:40)
[23:34:32 ERROR]:       at eu.mcdb.spicord.embed.Embed.fromJson(Embed.java:325)
[23:34:32 ERROR]:       at eu.mcdb.ban_announcer.BanAnnouncer$MessageFormatter.format(BanAnnouncer.java:156)
[23:34:32 ERROR]:       at eu.mcdb.ban_announcer.BanAnnouncer.lambda$new$0(BanAnnouncer.java:66)
[23:34:32 ERROR]:       at eu.mcdb.ban_announcer.BanAnnouncer.lambda$new$4(BanAnnouncer.java:73)
[23:34:32 ERROR]:       at eu.mcdb.ban_announcer.BanAnnouncer.handlePunishmentAction(BanAnnouncer.java:95)
[23:34:32 ERROR]:       at eu.mcdb.ban_announcer.listener.LiteBans$LiteBansListener.handleEntry(LiteBans.java:139)
[23:34:32 ERROR]:       at eu.mcdb.ban_announcer.listener.LiteBans$LiteBansListener.entryAdded(LiteBans.java:72)
[23:34:32 ERROR]:       at litebans.fY.a(fY.java:13)
[23:34:32 ERROR]:       at litebans.gB.run(gB.java:57)
[23:34:32 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[23:34:32 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[23:34:32 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:834)
[23:34:32 ERROR]: Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 142 path $.embed.description
[23:34:32 ERROR]:       at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
[23:34:32 ERROR]:       at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491)
[23:34:32 ERROR]:       at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
[23:34:32 ERROR]:       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:214)
[23:34:32 ERROR]:       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
[23:34:32 ERROR]:       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
[23:34:32 ERROR]:       at com.google.gson.Gson.fromJson(Gson.java:887)
[23:34:32 ERROR]:       ... 16 more`

**Comment by cferreras** [comment]
The problem was in the embed and that it did not reload the plugin correctly.
