### ISSUE TITLE
Ban Announcer not enabling, Spicord works fine

### ISSUE THREAD

**Issue by TaminoPalm** [Spicord/BanAnnouncer#37]
It does not even generate a config ;(

[20:01:24 WARN]: Exception encountered when loading plugin: BanAnnouncer
java.lang.NullPointerException: Cannot invoke "org.spicord.Spicord.addEventListener(org.spicord.event.SpicordEvent, org.spicord.event.EventHandler)" because the return value of "org.spicord.Spicord.getInstance()" is null
        at eu.mcdb.ban_announcer.bungee.BanAnnouncerBungee.onEnable(BanAnnouncerBungee.java:35) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:300) ~[Bungee.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:289) ~[Bungee.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[Bungee.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[Bungee.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]

**Comment by TaminoPalm** [comment]
[20:01:24 WARN]: Exception encountered when loading plugin: BanAnnouncer
java.lang.NullPointerException: Cannot invoke "org.spicord.Spicord.addEventListener(org.spicord.event.SpicordEvent, org.spicord.event.EventHandler)" because the return value of "org.spicord.Spicord.getInstance()" is null
        at eu.mcdb.ban_announcer.bungee.BanAnnouncerBungee.onEnable(BanAnnouncerBungee.java:35) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:300) ~[Bungee.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:289) ~[Bungee.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[Bungee.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[Bungee.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]

**Comment by OopsieWoopsie** [comment]
Hi, can you send me your full server log?

**Comment by TaminoPalm** [comment]
After a full server restart there is now a config, but is there a way to reload banannouncer? Cause i dont want to restart ant kick all my players.

**Comment by OopsieWoopsie** [comment]
In order to fix this issue I will need you to provide me a clean server startup log, otherwise I can't help. And from what you just said ("After a full bungee restart there is now a config") it makes me think that the error was caused because you tried to load the plugin in a non-standard way, for example by using some PlugMan-like plugin...
