### ISSUE TITLE
An uncaught exception was thrown by a LiteBans API event listener

### ISSUE THREAD

**Issue by KrusteF** [Spicord/BanAnnouncer#41]
I just tried the plugin on my server (paper 1.12.2), but it gives me an error every time a command is being used

[23:29:33 INFO]: KrusteF issued server command: /warn KrusteF -s test
[23:29:33 ERROR]: [LiteBans] An uncaught exception was thrown by a LiteBans API event listener.
[23:29:33 WARN]: java.lang.IllegalAccessError: tried to access class eu.mcdb.ban_announcer.BanAnnouncer$MessageFormatter from class eu.mcdb.ban_announcer.BanAnnouncer
[23:29:33 WARN]:        at eu.mcdb.ban_announcer.BanAnnouncer.lambda$new$0(BanAnnouncer.java:63)
[23:29:33 WARN]:        at eu.mcdb.ban_announcer.BanAnnouncer.lambda$new$4(BanAnnouncer.java:77)
[23:29:33 WARN]:        at eu.mcdb.ban_announcer.BanAnnouncer.handlePunishmentAction(BanAnnouncer.java:103)
[23:29:33 WARN]:        at eu.mcdb.ban_announcer.listener.LiteBans$LiteBansListener.handleEntry(LiteBans.java:141)
[23:29:33 WARN]:        at eu.mcdb.ban_announcer.listener.LiteBans$LiteBansListener.entryAdded(LiteBans.java:72)
[23:29:33 WARN]:        at litebans.fj.b(fj.java:13)
[23:29:33 WARN]:        at litebans.jX.run(jX.java:57)
[23:29:33 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[23:29:33 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[23:29:33 WARN]:        at java.lang.Thread.run(Thread.java:748)
[23:29:33 ERROR]: [LiteBans] An uncaught exception was thrown by a LiteBans API event listener.
[23:29:33 ERROR]: [LiteBans] This is likely a bug in a plugin which is using the LiteBans API.
[23:29:33 WARN]: java.lang.NullPointerException
[23:29:33 WARN]:        at eu.mcdb.ban_announcer.listener.LiteBans$LiteBansListener.entryAdded(LiteBans.java:69)
[23:29:33 WARN]:        at litebans.fj.b(fj.java:13)
[23:29:33 WARN]:        at litebans.jX.run(jX.java:57)
[23:29:33 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[23:29:33 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[23:29:33 WARN]:        at java.lang.Thread.run(Thread.java:748)
[23:29:33 ERROR]: [LiteBans] An uncaught exception was thrown by a LiteBans API event listener.
[23:29:33 ERROR]: [LiteBans] This is likely a bug in a plugin which is using the LiteBans API.
[23:29:33 WARN]: java.lang.NullPointerException
[23:29:33 WARN]:        at eu.mcdb.ban_announcer.listener.LiteBans$LiteBansListener.entryAdded(LiteBans.java:69)
[23:29:33 WARN]:        at litebans.fj.b(fj.java:13)
[23:29:33 WARN]:        at litebans.jX.run(jX.java:57)
[23:29:33 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[23:29:33 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[23:29:33 WARN]:        at java.lang.Thread.run(Thread.java:748)
[23:29:33 ERROR]: [LiteBans] An uncaught exception was thrown by a LiteBans API event listener.
[23:29:33 WARN]: java.lang.IllegalAccessError: tried to access class eu.mcdb.ban_announcer.BanAnnouncer$MessageFormatter from class eu.mcdb.ban_announcer.BanAnnouncer
[23:29:33 WARN]:        at eu.mcdb.ban_announcer.BanAnnouncer.lambda$new$0(BanAnnouncer.java:63)
[23:29:33 WARN]:        at eu.mcdb.ban_announcer.BanAnnouncer.lambda$new$4(BanAnnouncer.java:77)
[23:29:33 WARN]:        at eu.mcdb.ban_announcer.BanAnnouncer.handlePunishmentAction(BanAnnouncer.java:103)
[23:29:33 WARN]:        at eu.mcdb.ban_announcer.listener.LiteBans$LiteBansListener.handleEntry(LiteBans.java:141)
[23:29:33 WARN]:        at eu.mcdb.ban_announcer.listener.LiteBans$LiteBansListener.entryAdded(LiteBans.java:72)
[23:29:33 WARN]:        at litebans.fj.b(fj.java:13)
[23:29:33 WARN]:        at litebans.jX.run(jX.java:57)
[23:29:33 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[23:29:33 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[23:29:33 WARN]:        at java.lang.Thread.run(Thread.java:748)
[23:29:33 INFO]: [Silent] KrusteF has been Warned by KrusteF
» Reason: test
[23:29:33 INFO]: [BanAnnouncer] The punishment message was sent.

**Comment by OopsieWoopsie** [comment]
Hi, this is probably because:

1. You have a bad config, probably you broke its format (seems to be related with the ignore-silent option)
2. You have used the /reload command of your server, you should not do that.

Try deleting the config file and let it regenerate again by making a clean restart of your server.
