### ISSUE TITLE
ban announcer issue

### ISSUE THREAD

**Issue by JininaDukiso** [Spicord/BanAnnouncer#61]
Hi, 3 days ago ban announcer stopped logging punishments. I get this error code when wanting to use any punishment commands: 
[17:11:31 ERROR]: Could not pass event PunishmentEvent to BanAnnouncer v2.3.0
java.lang.LinkageError: loader constraint violation: loader 'BanAnnouncer_2.3.0.jar' @3b25bd64 wants to load interface net.dv8tion.jda.api.JDA. A different interface with the same name was previously loaded by 'Spicord_4.0.0.jar' @48df51e3. (net.dv8tion.jda.api.JDA is in unnamed module of loader 'Spicord_4.0.0.jar' @48df51e3, parent loader 'app')
        at eu.mcdb.ban_announcer.BanAnnouncer.sendDiscordMessage(BanAnnouncer.java:113) ~[BanAnnouncer_2.3.0.jar:?]
        at eu.mcdb.ban_announcer.BanAnnouncer.handlePunishmentAction(BanAnnouncer.java:104) ~[BanAnnouncer_2.3.0.jar:?]
        at eu.mcdb.ban_announcer.listener.AdvancedBan.onPunishmentAction(AdvancedBan.java:89) ~[BanAnnouncer_2.3.0.jar:?]
        at eu.mcdb.ban_announcer.bukkit.listener.AdvancedBanListener.onPunishment(AdvancedBanListener.java:30) ~[BanAnnouncer_2.3.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor437.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-279]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-279]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-279]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-279]
        at me.leoko.advancedban.bukkit.BukkitMethods.lambda$callPunishmentEvent$7(BukkitMethods.java:370) ~[AdvancedBan-Bundle-2.3.0-RELEASE.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-279]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1559) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-279]
        at java.lang.Thread.run(Thread.java:831) [?:?]
        
        
What can I do?

**Comment by JininaDukiso** [comment]
Hola, perdona por tardar, por temas de mi vida me ha sido imposible trabajar en el servidor esta semana. 
He instalado el plugin que me comentas y recibo este mensaje cuando uso el command: [07:49:39 INFO]: Failed to get findClass() method: org.bukkit.plugin.java.PluginClassLoader.findClass(java.lang.String,boolean)

**Comment by JininaDukiso** [comment]
Intente lo que comentas en el otro issue de poner los files .txt hice un restart de spicord y aun asi sigo con el mismo error :/

**Comment by OopsieWoopsie** [comment]
Hola, disculpa por la demora :/

Justo acabo de hacer un fix para FindClass, ahora funciona en cualquier version de spigot.
https://github.com/OopsieWoopsie/FindClass/releases/download/2.0/FindClass-2.0.jar

Si aún tienes el mismo problema me gustaria poder seguir ayudandote a solucionarlo

**Comment by JininaDukiso** [comment]
Hola buenas! nos dimos cuenta que otro plugin que se usa bastante, interfiere con su plugin. Instalamos el update de Skoice que dejó de usar Skript y cambió a lo que sospecho a JDA de discord. Al quitarlo su plugin de bannanouncer y etc funcionaba de nuevo.

**Comment by OopsieWoopsie** [comment]
Es bueno saberlo, gracias por decirlo :smile:
