### ISSUE TITLE
BanAnnouncer issue

### ISSUE THREAD

**Issue by Minoo1233** [Spicord/BanAnnouncer#63]
Hi, I have a problem, and it is that about 4 days ago the plugin stopped announcing the bannings, and when checking the console I noticed the following error

[19:28:38 ERROR]: Could not pass event PunishmentEvent to BanAnnouncer v2.3.0
java.lang.LinkageError: loader constraint violation: loader 'BanAnnouncer_2.3.0.jar' @6a78e6d0 wants to load interface net.dv8tion.jda.api.JDA. A different interface with the same name was previously loaded by 'Spicord_4.0.0.jar' @39deea1. (net.dv8tion.jda.api.JDA is in unnamed module of loader 'Spicord_4.0.0.jar' @39deea1, parent loader 'app')
        at eu.mcdb.ban_announcer.BanAnnouncer.sendDiscordMessage(BanAnnouncer.java:113) ~[BanAnnouncer_2.3.0.jar:?]
        at eu.mcdb.ban_announcer.BanAnnouncer.handlePunishmentAction(BanAnnouncer.java:104) ~[BanAnnouncer_2.3.0.jar:?]
        at eu.mcdb.ban_announcer.listener.AdvancedBan.onPunishmentAction(AdvancedBan.java:89) ~[BanAnnouncer_2.3.0.jar:?]
        at eu.mcdb.ban_announcer.bukkit.listener.AdvancedBanListener.onPunishment(AdvancedBanListener.java:30) ~[BanAnnouncer_2.3.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1444.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-325]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-325]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-325]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[patched_1.17.1.jar:git-Paper-325]
        at me.leoko.advancedban.bukkit.BukkitMethods.lambda$callPunishmentEvent$7(BukkitMethods.java:370) ~[AdvancedBan-Bundle-2.3.0-RELEASE (1).jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-325]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-325]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1559) ~[patched_1.17.1.jar:git-Paper-325]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-325]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-325]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-325]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-325]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]

**Comment by Minoo1233** [comment]
Ya lo Solucione
