### ISSUE TITLE
Ban announcer stopped working

### ISSUE THREAD

**Issue by Chiarchiaooo** [Spicord/BanAnnouncer#68]
Hi, i recently installed ban announcer, i got everything set up and working, but out of nowhere, ban announcer stopped sending messages to my discord server, with no error in console, i tried to reload it with plugman and again no errors but when i tried to restart spicord with its restart command on my console appeared this: 

[19:07:41 WARN]:        at Spicord_4.1.0.jar[19:13:36 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[19:13:36 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[19:13:36 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[19:13:36 WARN]:        at BanAnnouncer_2.5.0.jar//eu.mcdb.ban_announcer.listener.LiteBansListener$InternalListener.entryAdded(LiteBansListener.java:132)
[19:13:36 WARN]:        at LiteBans.jar//litebans.fj.b(fj.java:13)
[19:13:36 WARN]:        at LiteBans.jar//litebans.jX.run(jX.java:57)
[19:13:36 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[19:13:36 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[19:13:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

now, i would like to know where is the problem (if in spicord, ban announcer or litebans) because i would like to continue using this plugin (also maybe because it's the only doing this)

**Comment by OopsieWoopsie** [comment]
Hi, please provide the full error log, you didn't included the top line that says what the error actually is.

**Comment by Chiarchiaooo** [comment]
Hi, i don't know why but it started working again on its own, sorry
