### ISSUE TITLE
An uncaught exception was thrown by a LiteBans API event listener.

### ISSUE THREAD

**Issue by Zynaxwastaken** [Spicord/BanAnnouncer#76]
Hello, whenever a punishment is sent to discord, I get errors in my server console.
How do I fix this?

```
[Sun, 13. Mar 2022 20:17:01 GMT INFO] Zynax_ issued server command: /warn Zynax_ test
[Sun, 13. Mar 2022 20:17:01 GMT ERROR] An uncaught exception was thrown by a LiteBans API event listener.
[Sun, 13. Mar 2022 20:17:01 GMT ERROR] This is likely a bug in a plugin which is using the LiteBans API.
[Sun, 13. Mar 2022 20:17:01 GMT WARN] java.lang.NullPointerException: Cannot invoke "org.spicord.bot.DiscordBot.getJda()" because "this.bot" is null
[Sun, 13. Mar 2022 20:17:01 GMT WARN] at BanAnnouncer_2.6.0.jar//eu.mcdb.ban_announcer.BanAnnouncer.sendDiscordMessage(BanAnnouncer.java:111)
[Sun, 13. Mar 2022 20:17:01 GMT WARN] at BanAnnouncer_2.6.0.jar//eu.mcdb.ban_announcer.BanAnnouncer.handlePunishmentAction(BanAnnouncer.java:102)
[Sun, 13. Mar 2022 20:17:01 GMT WARN] at BanAnnouncer_2.6.0.jar//eu.mcdb.ban_announcer.PunishmentListener.handlePunishment(PunishmentListener.java:12)
[Sun, 13. Mar 2022 20:17:01 GMT WARN] at BanAnnouncer_2.6.0.jar//eu.mcdb.ban_announcer.listener.LiteBansListener.handleEntry(LiteBansListener.java:108)
[Sun, 13. Mar 2022 20:17:01 GMT WARN] at BanAnnouncer_2.6.0.jar//eu.mcdb.ban_announcer.listener.LiteBansListener$InternalListener.entryAdded(LiteBansListener.java:138)
[Sun, 13. Mar 2022 20:17:01 GMT WARN] at LiteBans.jar//litebans.hW.b(hW.java:13)
[Sun, 13. Mar 2022 20:17:01 GMT WARN] at LiteBans.jar//litebans.js.run(js.java:57)
[Sun, 13. Mar 2022 20:17:01 GMT WARN] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[Sun, 13. Mar 2022 20:17:01 GMT WARN] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[Sun, 13. Mar 2022 20:17:01 GMT WARN] at java.base/java.lang.Thread.run(Thread.java:833)
[Sun, 13. Mar 2022 20:17:01 GMT INFO] Zynax_ warned Zynax_ for 'test'
[Sun, 13. Mar 2022 20:17:01 GMT INFO] The punishment message was sent.
```

**Comment by anvorgesa** [comment]
Hi, please send your full server log, from the start until that error happens. Otherwise I won't be able to help.

**Comment by Zynaxwastaken** [comment]
The issue doesn't seem to be happening anymore, not sure what fixed it as I didn't change anything
