### ISSUE TITLE
Cannot invoke "org.spicord.bot.DiscordBot.getJda()" because "this.bot" is null

### ISSUE THREAD

**Issue by Etienne13435** [Spicord/BanAnnouncer#82]
Hey good evening,
currently i have an issue after typing anything from liberty bans(e.g.mute, kic,ban, etc) this error pops up in my console and i dont get a embed/message in the discord channel i set it too.

[00:06:48 WARN]: [space.arim.omnibus.defaultimpl.events.EventFire] Exception while calling event space.arim.libertybans.core.event.PostPardonEventImpl@6d9f4ca2 for event consumer eu.mcdb.ban_announcer.listener.LibertyBansListener$$Lambda$10451/0x0000000802bc48d0@68b94df9
java.lang.NullPointerException: Cannot invoke "org.spicord.bot.DiscordBot.getJda()" because "this.bot" is null
        at eu.mcdb.ban_announcer.BanAnnouncer.sendDiscordMessage(BanAnnouncer.java:111) ~[BanAnnouncer_2.6.0.jar:?]
        at eu.mcdb.ban_announcer.BanAnnouncer.handlePunishmentAction(BanAnnouncer.java:102) ~[BanAnnouncer_2.6.0.jar:?]
        at eu.mcdb.ban_announcer.PunishmentListener.handlePunishment(PunishmentListener.java:12) ~[BanAnnouncer_2.6.0.jar:?]
        at eu.mcdb.ban_announcer.listener.LibertyBansListener.handle(LibertyBansListener.java:133) ~[BanAnnouncer_2.6.0.jar:?]
        at eu.mcdb.ban_announcer.listener.LibertyBansListener.onPostPardonEvent(LibertyBansListener.java:69) ~[BanAnnouncer_2.6.0.jar:?]
        at space.arim.omnibus.events.EventConsumer.accept(EventConsumer.java:30) ~[LibertyBans_Release-1.0.1.jar:?]
        at space.arim.omnibus.defaultimpl.events.EventFire.callSyncListener(EventFire.java:66) ~[LibertyBans_Release-1.0.1.jar:?]
        at space.arim.omnibus.defaultimpl.events.EventFire.callAsyncListeners(EventFire.java:84) ~[LibertyBans_Release-1.0.1.jar:?]
        at space.arim.omnibus.defaultimpl.events.DefaultEvents.fireAsyncEventCommon(DefaultEvents.java:69) ~[LibertyBans_Release-1.0.1.jar:?]
        at space.arim.omnibus.defaultimpl.events.DefaultEvents.fireAsyncEvent(DefaultEvents.java:78) ~[LibertyBans_Release-1.0.1.jar:?]
        at space.arim.libertybans.core.commands.AbstractSubCommandGroup.fireWithTimeout(AbstractSubCommandGroup.java:116) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.core.commands.UnpunishCommands$Execution.lambda$sendSuccess$5(UnpunishCommands.java:211) ~[LibertyBans-ClassLoader:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
        at space.arim.omnibus.util.concurrent.impl.AbstractFactoryOfTheFuture.lambda$copyStage0$3(AbstractFactoryOfTheFuture.java:139) ~[LibertyBans_Release-1.0.1.jar:?]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by LpDeath** [comment]
yeah, i have this problem too

**Comment by anvorgesa** [comment]
Closing this issue because it was solved from the Discord server.
