### ISSUE TITLE
Spicord/Banannouncer is throwing errors when banning players

### ISSUE THREAD

**Issue by Impactic48** [Spicord/BanAnnouncer#85]
When banning a player I get the following error:
(Spicord and Banannouncer configs are included below)

```tempban normalizer 1s -s
[18:45:58 ERROR]: [LiteBans] An uncaught exception was thrown by a LiteBans API event listener.
[18:45:58 ERROR]: [LiteBans] This is likely a bug in a plugin which is using the LiteBans API.
[18:45:58 WARN]: java.lang.NullPointerException: Cannot invoke "org.spicord.bot.DiscordBot.getJda()" because "this.bot" is null
[18:45:58 WARN]:        at BanAnnouncer_2.5.3.jar//eu.mcdb.ban_announcer.BanAnnouncer.sendDiscordMessage(BanAnnouncer.java:111)
[18:45:58 WARN]:        at BanAnnouncer_2.5.3.jar//eu.mcdb.ban_announcer.BanAnnouncer.handlePunishmentAction(BanAnnouncer.java:102)
[18:45:58 WARN]:        at BanAnnouncer_2.5.3.jar//eu.mcdb.ban_announcer.PunishmentListener.handlePunishment(PunishmentListener.java:12)
[18:45:58 WARN]:        at BanAnnouncer_2.5.3.jar//eu.mcdb.ban_announcer.listener.LiteBansListener.handleEntry(LiteBansListener.java:108)
[18:45:58 WARN]:        at BanAnnouncer_2.5.3.jar//eu.mcdb.ban_announcer.listener.LiteBansListener$InternalListener.entryAdded(LiteBansListener.java:138)
[18:45:58 WARN]:        at LiteBans.jar//litebans.eA.b(eA.java:13)
[18:45:58 WARN]:        at LiteBans.jar//litebans.jv.run(jv.java:57)
[18:45:58 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:45:58 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:45:58 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[18:45:58 ERROR]: [LiteBans] An uncaught exception was thrown by a LiteBans API event listener.
[18:45:58 ERROR]: [LiteBans] This is likely a bug in a plugin which is using the LiteBans API.
[18:45:58 WARN]: java.lang.NullPointerException: Cannot invoke "org.spicord.bot.DiscordBot.getJda()" because "this.bot" is null
[18:45:58 WARN]:        at BanAnnouncer_2.5.3.jar//eu.mcdb.ban_announcer.BanAnnouncer.sendDiscordMessage(BanAnnouncer.java:111)
[18:45:58 WARN]:        at BanAnnouncer_2.5.3.jar//eu.mcdb.ban_announcer.BanAnnouncer.handlePunishmentAction(BanAnnouncer.java:102)
[18:45:58 WARN]:        at BanAnnouncer_2.5.3.jar//eu.mcdb.ban_announcer.PunishmentListener.handlePunishment(PunishmentListener.java:12)
[18:45:58 WARN]:        at BanAnnouncer_2.5.3.jar//eu.mcdb.ban_announcer.listener.LiteBansListener.handleEntry(LiteBansListener.java:108)
[18:45:58 WARN]:        at BanAnnouncer_2.5.3.jar//eu.mcdb.ban_announcer.listener.LiteBansListener$InternalListener.entryAdded(LiteBansListener.java:138)
[18:45:58 WARN]:        at LiteBans.jar//litebans.eA.b(eA.java:13)
[18:45:58 WARN]:        at LiteBans.jar//litebans.jv.run(jv.java:57)
[18:45:58 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:45:58 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:45:58 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[18:45:58 ERROR]: [LiteBans] An uncaught exception was thrown by a LiteBans API event listener.
[18:45:58 ERROR]: [LiteBans] This is likely a bug in a plugin which is using the LiteBans API.
[18:45:58 WARN]: java.lang.NullPointerException: Cannot invoke "org.spicord.bot.DiscordBot.getJda()" because "this.bot" is null
[18:45:58 WARN]:        at BanAnnouncer_2.5.3.jar//eu.mcdb.ban_announcer.BanAnnouncer.sendDiscordMessage(BanAnnouncer.java:111)
[18:45:58 WARN]:        at BanAnnouncer_2.5.3.jar//eu.mcdb.ban_announcer.BanAnnouncer.handlePunishmentAction(BanAnnouncer.java:102)
[18:45:58 WARN]:        at BanAnnouncer_2.5.3.jar//eu.mcdb.ban_announcer.PunishmentListener.handlePunishment(PunishmentListener.java:12)
[18:45:58 WARN]:        at BanAnnouncer_2.5.3.jar//eu.mcdb.ban_announcer.listener.LiteBansListener.handleEntry(LiteBansListener.java:108)
[18:45:58 WARN]:        at BanAnnouncer_2.5.3.jar//eu.mcdb.ban_announcer.listener.LiteBansListener$InternalListener.entryAdded(LiteBansListener.java:138)
[18:45:58 WARN]:        at LiteBans.jar//litebans.eA.b(eA.java:13)
[18:45:58 WARN]:        at LiteBans.jar//litebans.jv.run(jv.java:57)
[18:45:58 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:45:58 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:45:58 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[18:45:58 INFO]: [Silent] Console tempbanned Normalizer for 1 second for Violating Server Rules```

-------------------------------------------------------------------------------------

BanAnnouncer Config:
```# The channel(s) id where the messages will be sent
# If you don't know how to get a channel id... https://www.google.com/?q=discord+how+to+get+channel+id
channels-to-announce:
  - 92801260542613****

# If the text is empty (nothing between the double quotes),
#    the message will not be sent (a.k.a. the message is "disabled"), for example:
#
#    kick: "" <-- this will disable the message
#
#    If you don't want to use embed messages you can use pure text, for ex.:
#
#    kick: "The player %player% was kicked by %staff%"
#
#    
# Variables are self-explained...
messages:
  kick:      ""
  note:      ""
  jail:      "{embed:jail}"
  ban:       "{embed:ban}"
  tempban:   "{embed:tempban}"
  mute:      ""
  tempmute:  ""
  banip:     "{embed:banip}"
  tempbanip: "{embed:tempbanip}"
  warn:      ""
  tempwarn:  ""
  unbanip:   "{embed:unbanip}"
  unwarn:    ""
  unmute:    ""
  unban:     "{embed:unban}"
  unnote:    ""
  unjail:    "{embed:unjail}"

# The plugin used for manage the punishments
# Possible values:
#     auto        = Auto detect
#     advancedban = Use AdvancedBan
#     litebans    = Use LiteBans
#     maxbans     = Use MaxBansPlus
#     libertybans = Use LibertyBans
punishment-manager: litebans

# The plugin used for manage the jails (spigot-only)
# Possible values:
#     off         = Do not use this
#     essentials  = Use EssentialsX
#     betterjails = Use BetterJails 
jail-manager: off

# If it's set to false, the punishments made
#    with the '-s' flag of LiteBans will be sent anyways.
ignore-silent: false

# Name to show when the console does stuff
console-name: "Console"

# When a punishment expires this text will be added to the staff name
# for example:
# "X was unbanned by StaffName (Automatic)"
automatic: "Automatic"

# Do not change this or i'll eat your cookies
config-version: 4```

-------------------------------------------------------------------------------------

Spicord Config:
```# +--------------------------------------------------+
# | Project: Spicord                                 |
# | GitHub: https://github.com/OopsieWoopsie/Spicord |
# +--------------------------------------------------+

# Configuration version, don't change this.
config_version = 1


# Time in seconds that Spicord will wait for
# all external addons to register.
# Don't change this if you don't need this.
loadDelay = 10


# Leave it empty or delete the line to disable the footer
# or replace the text with whatever you want!
integrated_addon_footer = "Powered by Spicord v{version}"


[[bots]]
  name = "ArcadiaBot"
  enabled = true
  token = "*********************"
  command_support = true
  command_prefix = "-"
  addons = [
    "spicord::info",
    "spicord::players"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []


[jda_messages]
  enabled = true
  debug = true```

**Comment by anvorgesa** [comment]
You forgot to add the BanAnnouncer addon key into the addons list of your bot.
In the Spicord config, your addons list should look like this:
```toml
  addons = [
    "spicord::info",
    "spicord::players",
    "ban_announcer"
  ]
```
