### ISSUE TITLE
Bug/ Bungeecord

### ISSUE THREAD

**Issue by TypicalShavonne** [Spicord/BanAnnouncer#86]
[17:31:38 ERROR] [LiteBans]: An uncaught exception was thrown by a LiteBans API event listener.
[17:31:38 ERROR] [LiteBans]: This is likely a bug in a plugin which is using the LiteBans API.
[17:31:38 ERROR]: java.lang.NullPointerException: Cannot invoke "org.spicord.bot.DiscordBot.getJda()" because "this.bot" is null
[17:31:38 ERROR]:       at eu.mcdb.ban_announcer.BanAnnouncer.sendDiscordMessage(BanAnnouncer.java:111)
[17:31:38 ERROR]:       at eu.mcdb.ban_announcer.BanAnnouncer.handlePunishmentAction(BanAnnouncer.java:102)
[17:31:38 ERROR]:       at eu.mcdb.ban_announcer.PunishmentListener.handlePunishment(PunishmentListener.java:12)
[17:31:38 ERROR]:       at eu.mcdb.ban_announcer.listener.LiteBansListener.handleEntry(LiteBansListener.java:108)
[17:31:38 ERROR]:       at eu.mcdb.ban_announcer.listener.LiteBansListener$InternalListener.entryAdded(LiteBansListener.java:138)
[17:31:38 ERROR]:       at litebans.hW.b(hW.java:13)
[17:31:38 ERROR]:       at litebans.js.run(js.java:57)
[17:31:38 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[17:31:38 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[17:31:38 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by TypicalShavonne** [comment]
```
# +--------------------------------------------------+
# | Project: Spicord                                 |
# | GitHub: https://github.com/OopsieWoopsie/Spicord |
# +--------------------------------------------------+

# Configuration version, don't change this.
config_version = 1


# Time in seconds that Spicord will wait for
# all external addons to register.
# Don't change this if you don't need this.
loadDelay = 10


# Leave it empty or delete the line to disable the footer
# or replace the text with whatever you want!
integrated_addon_footer = "Powered by SimpPower"


[[bots]]
  name = "main"
  enabled =  true
  token = "_TOKEN_"
  command_support = true
  command_prefix = "-"
  addons = [
    "spicord::info",
    "spicord::plugins",
    "spicord::players",
    "ban_announcer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []


[jda_messages]
  enabled = true
  debug = true

```
