### ISSUE TITLE
LibertyBans punishment stopped sending messages to Discord

### ISSUE THREAD

**Issue by Boy0000** [Spicord/BanAnnouncer#87]
Not entirely sure why, but after we updated Velocity to update servers to 1.18.2,, the punishments were stopped from sending into the channel. Asked LibertyBans dev and said it sounded like a banannouncer issue.

Didnt change any configs or anything and using Spicord 4.2.1 and BA 2.6.0
Not sure if theres a known issue or something but yeah

Error:
```[14:13:36 WARN] [space.arim.omnibus.defaultimpl.events.EventFire]: Exception while calling event space.arim.libertybans.core.event.PostPunishEventImpl@53375144 for event consumer eu.mcdb.ban_announcer.listener.LibertyBansListener$$Lambda$1218/0x0000000801557400@4f17d368
java.lang.NullPointerException: Cannot invoke "org.spicord.bot.DiscordBot.getJda()" because "this.bot" is null
        at eu.mcdb.ban_announcer.BanAnnouncer.sendDiscordMessage(BanAnnouncer.java:111) ~[?:?]
        at eu.mcdb.ban_announcer.BanAnnouncer.handlePunishmentAction(BanAnnouncer.java:102) ~[?:?]
        at eu.mcdb.ban_announcer.PunishmentListener.handlePunishment(PunishmentListener.java:12) ~[?:?]
        at eu.mcdb.ban_announcer.listener.LibertyBansListener.handle(LibertyBansListener.java:133) ~[?:?]
        at eu.mcdb.ban_announcer.listener.LibertyBansListener.onPostPunishEvent(LibertyBansListener.java:65) ~[?:?]
        at space.arim.omnibus.events.EventConsumer.accept(EventConsumer.java:30) ~[?:?]
        at space.arim.omnibus.defaultimpl.events.EventFire.callSyncListener(EventFire.java:66) ~[?:?]
        at space.arim.omnibus.defaultimpl.events.EventFire.callAsyncListeners(EventFire.java:84) ~[?:?]
        at space.arim.omnibus.defaultimpl.events.DefaultEvents.fireAsyncEventCommon(DefaultEvents.java:69) ~[?:?]
        at space.arim.omnibus.defaultimpl.events.DefaultEvents.fireAsyncEvent(DefaultEvents.java:78) ~[?:?]
        at space.arim.libertybans.core.commands.AbstractSubCommandGroup.fireWithTimeout(AbstractSubCommandGroup.java:116) ~[?:?]
        at space.arim.libertybans.core.commands.PunishCommands$Execution.lambda$enforceAndSendSuccess$4(PunishCommands.java:246) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
        at space.arim.omnibus.util.concurrent.impl.AbstractFactoryOfTheFuture.lambda$copyStage0$3(AbstractFactoryOfTheFuture.java:139) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[14:13:36 INFO]: morb was warned.
```

Config:
```
# The channel(s) id where the messages will be sent
# If you don't know how to get a channel id... https://www.google.com/?q=discord+how+to+get+channel+id
channels-to-announce:
  - 449308250140049418

# If the text is empty (nothing between the double quotes),
#    the message will not be sent (a.k.a. the message is "disabled"), for example:
#
#    kick: "" <-- this will disable the message
#
#    If you don't want to use embed messages you can use pure text, for ex.:
#
#    kick: "The player %player% was kicked by %staff%"
#
#    
# Variables are self-explained...
messages:
  kick:      "{embed:kick}"
  note:      "{embed:note}"
  jail:      "{embed:jail}"
  ban:       "{embed:ban}"
  tempban:   "{embed:tempban}"
  mute:      "{embed:mute}"
  tempmute:  "{embed:tempmute}"
  banip:     "{embed:banip}"
  tempbanip: "{embed:tempbanip}"
  warn:      "{embed:warn}"
  tempwarn:  "{embed:tempwarn}"
  unbanip:   "{embed:unbanip}"
  unwarn:    "{embed:unwarn}"
  unmute:    "{embed:unmute}"
  unban:     "{embed:unban}"
  unnote:    "{embed:unnote}"
  unjail:    "{embed:unjail}"

# The plugin used for manage the punishments
# Possible values:
#     auto        = Auto detect
#     advancedban = Use AdvancedBan
#     litebans    = Use LiteBans
#     maxbans     = Use MaxBansPlus
punishment-manager: auto

# The plugin used for manage the jails (spigot-only)
# Possible values:
#     off         = Do not use this
#     essentials  = Use EssentialsX
#     betterjails = Use BetterJails 
jail-manager: off

# If it's set to false, the punishments made
#    with the '-s' flag of LiteBans will be sent anyways.
ignore-silent: false

# Name to show when the console does stuff
console-name: "Console"

# When a punishment expires this text will be added to the staff name
# for example:
# "X was unbanned by StaffName (Automatic)"
automatic: "Automatic"

# Do not change this or i'll eat your cookies
config-version: 4
```

**Comment by anvorgesa** [comment]
I will need to see your server startup log

**Comment by Boy0000** [comment]
```
[18:39:05] [main/INFO]: Booting up Velocity 3.1.2-SNAPSHOT (git-aa38d3e5-b137)...
[18:39:05] [main/INFO]: Loading localizations...
[18:39:05] [main/INFO]: Connections will use epoll channels, libdeflate (Linux x86_64) compression, OpenSSL 1.1.x (Linux x86_64) ciphers
[18:39:05] [main/INFO]: Loading plugins...
[18:39:05] [main/INFO]: [Loader] Loaded library 'toml4j-0.7.2.jar'
[18:39:05] [main/INFO]: [Loader] Loaded library 'JDA-4.2.1.jar'
[18:39:05] [main/INFO]: [Loader] Loaded library 'rhino-1.7.12.jar'
[18:39:05] [main/INFO]: [Loader] Loaded library 'snakeyaml-1.26.jar'
[18:39:05] [main/INFO]: Loaded 1 bots, 0 disabled.
[18:39:05] [main/INFO]: Loaded plugin spicord 4.2.x by Sheidy
[18:39:05] [main/INFO]: Loaded plugin libertybans 1.0.1 by A248
[18:39:05] [main/INFO]: Loaded plugin ban_announcer 2.5.2 by Sheidy
[18:39:05] [main/INFO]: Loaded plugin luckperms 5.4.21 by Luck
[18:39:05] [main/INFO]: Loaded plugin viaversion 4.2.1 by _MylesC, creeper123123321, Gerrygames, kennytv, Matsv
[18:39:05] [main/INFO]: Loaded plugin forceresourcepacks 1.11.20 (build 577) by Phoenix616
[18:39:05] [main/INFO]: Loaded plugin serverlistplus <UNKNOWN> by 
[18:39:05] [main/INFO]: Loaded plugin maintenance 4.0.1 by kennytv
[18:39:05] [main/INFO]: Loaded plugin rocketjoin 2.4 by Lorenzo0111
[18:39:05] [main/INFO]: Loaded plugin spark 1.6.2 by Luck
[18:39:05] [main/INFO]: Loaded plugin tab 3.1.1 by NEZNAMY
[18:39:05] [main/INFO]: Loaded plugin venturechat 3.3.2 by Aust1n46
[18:39:05] [main/INFO]: Loaded 12 plugins
[18:39:05] [Velocity Async Event Executor - #0/INFO]:         __    
[18:39:05] [Velocity Async Event Executor - #0/INFO]:   |    |__)   LuckPerms v5.4.21
[18:39:05] [Velocity Async Event Executor - #0/INFO]:   |___ |      Running on Velocity - Velocity
[18:39:05] [Velocity Async Event Executor - #0/INFO]: 
[18:39:05] [Velocity Async Event Executor - #0/INFO]: Loading configuration...
[18:39:06] [Velocity Async Event Executor - #0/INFO]: Loading storage provider... [H2]
[18:39:06] [Velocity Async Event Executor - #0/INFO]: Loading internal permission managers...
[18:39:06] [Velocity Async Event Executor - #0/INFO]: Performing initial data load...
[18:39:06] [Velocity Async Event Executor - #0/INFO]: Successfully enabled. (took 649ms)
[18:39:06] [Velocity Async Event Executor - #0/INFO]: Registered addon 'Server Information' (spicord::info) by Sheidy
[18:39:06] [Velocity Async Event Executor - #0/INFO]: Registered addon 'Plugin List' (spicord::plugins) by Sheidy
[18:39:06] [Velocity Async Event Executor - #0/INFO]: Registered addon 'Player List' (spicord::players) by Sheidy
[18:39:06] [Velocity Async Event Executor - #0/INFO]: Starting the bots...
[18:39:06] [Velocity Async Event Executor - #0/INFO]: Starting bot 'default'.
[18:39:06] [Velocity Async Event Executor - #0/INFO]: Conducting START...
[18:39:06] [Velocity Async Event Executor - #0/INFO]: LibertyBansTemporaryPool-HyperSQL - Starting...
[18:39:06] [ForkJoinPool.commonPool-worker-1/WARN]: The addon with the id 'ban_announcer' was not found.
[18:39:07] [Velocity Async Event Executor - #0/INFO]: LibertyBansTemporaryPool-HyperSQL - Driver does not support get/set network timeout for connections. (feature not supported)
[18:39:07] [Velocity Async Event Executor - #0/INFO]: LibertyBansTemporaryPool-HyperSQL - Added connection org.hsqldb.jdbc.JDBCConnection@798fa927
[18:39:07] [Velocity Async Event Executor - #0/INFO]: LibertyBansTemporaryPool-HyperSQL - Start completed.
[18:39:07] [Velocity Async Event Executor - #0/INFO]: LibertyBansTemporaryPool-HyperSQL - Shutdown initiated...
[18:39:07] [Velocity Async Event Executor - #0/INFO]: LibertyBansTemporaryPool-HyperSQL - Shutdown completed.
[18:39:07] [Velocity Async Event Executor - #0/INFO]: LibertyBansPool-HyperSQL - Starting...
[18:39:07] [Velocity Async Event Executor - #0/INFO]: LibertyBansPool-HyperSQL - Driver does not support get/set network timeout for connections. (feature not supported)
[18:39:07] [Velocity Async Event Executor - #0/INFO]: LibertyBansPool-HyperSQL - Added connection org.hsqldb.jdbc.JDBCConnection@4132d45e
[18:39:07] [Velocity Async Event Executor - #0/INFO]: LibertyBansPool-HyperSQL - Start completed.
[18:39:07] [Velocity Async Event Executor - #0/INFO]: Flyway Community Edition 8.2.0 by Redgate
[18:39:07] [Velocity Async Event Executor - #0/INFO]: Database: jdbc:hsqldb:file:/home/container/plugins/libertybans/hypersql/punishments-database;sql.enforce_refs=true;hsqldb.tx_interrupt_rollback=true;sql.sys_index_names=true;hsqldb.default_table_type=cached;sql.enforce_types=true;sql.restrict_exec=true;sql.enforce_names=true (HSQL Database Engine 2.6)
[18:39:07] [Velocity Async Event Executor - #0/INFO]: Successfully validated 7 migrations (execution time 00:00.027s)
[18:39:07] [Velocity Async Event Executor - #0/INFO]: Current version of schema "PUBLIC": 16
[18:39:07] [Velocity Async Event Executor - #0/INFO]: Schema "PUBLIC" is up to date. No migration necessary.
[18:39:08] [Velocity Async Event Executor - #0/INFO]: Finished START in 1.580 seconds
[18:39:08] [Velocity Async Event Executor - #0/INFO]: [AutoDetect] Using LibertyBans as the punishment manager.
[18:39:08] [Velocity Async Event Executor - #0/INFO]: Registered addon 'BanAnnouncer' (ban_announcer) by Sheidy
[18:39:08] [Velocity Async Event Executor - #0/INFO]: Loading config!
[18:39:08] [Velocity Async Event Executor - #0/INFO]: Loaded config.yml
[18:39:08] [Velocity Async Event Executor - #0/INFO]: Loaded players.conf
[18:39:08] [Velocity Async Event Executor - #0/INFO]: Debug level: FINE
[18:39:08] [Velocity Async Event Executor - #0/INFO]: Found locale en
[18:39:08] [Velocity Async Event Executor - #0/INFO]: Loading packs:
[18:39:08] [Velocity Async Event Executor - #0/INFO]: game - 1 variants
[18:39:08] [Velocity Async Event Executor - #0/WARN]: No empty pack defined!
[18:39:08] [Velocity Async Event Executor - #0/INFO]: Loading global assignment...
[18:39:08] [Velocity Async Event Executor - #0/INFO]: Loading server assignments...
[18:39:08] [Velocity Async Event Executor - #0/INFO]: Loading assignment for server global...
[18:39:08] [Velocity Async Event Executor - #0/INFO]: Loaded joined.yml
[18:39:08] [Velocity Async Event Executor - #0/INFO]: Update notifications are disabled!
[18:39:08] [Velocity Async Event Executor - #0/INFO]: [Core] Reloading configuration...
[18:39:08] [Velocity Async Event Executor - #0/INFO]: [Core] Loaded configuration: ServerStatusConf
[18:39:08] [Velocity Async Event Executor - #0/WARN]: [Core] Unknown configuration property: Stats @ PluginConf
[18:39:08] [Velocity Async Event Executor - #0/WARN]: [Core] Unknown configuration property: Samples @ PluginConf
[18:39:08] [Velocity Async Event Executor - #0/INFO]: [Core] Loaded configuration: PluginConf
[18:39:08] [Velocity Async Event Executor - #0/INFO]: [Core] Reloading saved player identities...
[18:39:08] [Velocity Async Event Executor - #0/INFO]: Successfully loaded!
[18:39:08] [Velocity Async Event Executor - #0/INFO]: Enabled ServerListPlus integration!
[18:39:08] [Velocity Async Event Executor - #0/INFO]: RocketJoin loaded!
[18:39:08] [Velocity Async Event Executor - #0/INFO]: If you experience tablist prefix/suffix not working and global playerlist duplicating players, toggle "use-online-uuid-in-tablist" option in config.yml (set it to opposite value).
[18:39:08] [Velocity Async Event Executor - #0/INFO]: Enabled in 40ms
[18:39:09] [Via-Mappingloader-0/INFO]: Loading 1.12 -> 1.13 mappings...
[18:39:09] [Via-Mappingloader-1/INFO]: Loading 1.13 -> 1.13.2 mappings...
[18:39:09] [Via-Mappingloader-2/INFO]: Loading 1.13.2 -> 1.14 mappings...
[18:39:09] [Via-Mappingloader-3/INFO]: Loading 1.14 -> 1.15 mappings...
[18:39:09] [Via-Mappingloader-4/INFO]: Loading 1.15 -> 1.16 mappings...
[18:39:09] [Via-Mappingloader-5/INFO]: Loading 1.16 -> 1.16.2 mappings...
[18:39:09] [Via-Mappingloader-1/INFO]: Loading 1.16.2 -> 1.17 mappings...
[18:39:09] [Via-Mappingloader-0/INFO]: Loading block connection mappings ...
[18:39:09] [Via-Mappingloader-3/INFO]: Loading 1.17 -> 1.18 mappings...
[18:39:09] [Velocity Async Event Executor - #0/INFO]: Replacing channel initializers; you can safely ignore the following two warnings.
[18:39:09] [Velocity Async Event Executor - #0/WARN]: The server channel initializer has been replaced by java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:39:09] [Velocity Async Event Executor - #0/WARN]: The backend channel initializer has been replaced by java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:39:09] [Velocity Task Scheduler - #1/INFO]: ViaVersion detected lowest supported version by the proxy: 1.13 (393)
[18:39:09] [Velocity Task Scheduler - #1/INFO]: Highest supported version by the proxy: 1.18.2 (758)
[18:39:09] [Netty epoll Boss #0/INFO]: Listening on /[0:0:0:0:0:0:0:0%0]:25565
[18:39:09] [main/INFO]: Done (4.8s)!
[18:39:09] [Velocity Task Scheduler - #0/INFO]: Finished mapping loading, shutting down loader executor!
```

**Comment by Pabsb** [comment]
`because "this.bot" is null` in your error. Bot token isn't set properly in Spicord is what it's saying. Double-check to make sure its the right token (You must have this saved and written down because if you try to display it in discord developer apps it will just regenerate it and create a new token which you then will need to update everywhere you use it.)

**Comment by Turjoy9** [comment]
@Pabsb I have 3 paper instances running the identical config file as the proxy and they are working fine. I can assure you that my error has nothing to do with me using the wrong token

**Comment by Boy0000** [comment]
Hmm yeah it had no issues until we updated Velocity around beginning of April.
No configs should have been changed but, i suppose ill remake the bot

**Comment by anvorgesa** [comment]
@Boy0000 sorry for my inactivity, I have been through a lot irl and have forgot to check github.

@Turjoy9 you are right, but the reason BanAnnouncer is registered too late is because it depends on LibertyBans and so BanAnnouncer will **wait** until LibertyBans loads, but at that time Spicord has already to loaded the bot and addons. This issue is present since the first releases of B.A. and can also occur on Spigot and BungeeCord if the punishment plugin that B.A. depends on takes too long to load.

@Pabsb it actually has nothing to do with the bot token, BanAnnouncer thinks it was loaded by Spicord at the right time so it expect to have the "bot" variable actually set, but Spicord never loaded it and thus never set the "bot" variable.

I have made an Spicord & B.A. build almost 20 days ago that attempts to fix the issues described here but they are only present on the Discord Support server. I will make some minimal changes to the builds and upload them on this GitHub issue in my next message.

**Comment by anvorgesa** [comment]
[latest.zip](https://github.com/Spicord/BanAnnouncer/files/8838305/latest.zip)

**Comment by Boy0000** [comment]
![image](https://user-images.githubusercontent.com/62521371/172017654-9f567bd0-a7d1-4c74-889c-da563256ce77.png)

can confirm the zip above fixes it 👍

**Comment by anvorgesa** [comment]
Thanks for the confirmation, I hope you enjoy the plugin :blush:
