### ISSUE TITLE
java.lang.RuntimeException: java.lang.IllegalStateException: Invalid value on line 30: addons = ban_announcer"

### ISSUE THREAD

**Issue by JrBorshon** [Spicord/BanAnnouncer#90]
```
[00:54:13 INFO] [Spicord]: [Loader] Loaded library 'snakeyaml-1.26.jar'
[00:54:13 WARN]: Exception encountered when loading plugin: Spicord
java.lang.RuntimeException: java.lang.IllegalStateException: Invalid value on line 30: addons = ban_announcer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = an_announcer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = n_announcer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = _announcer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = announcer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = nnouncer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = nouncer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = ouncer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = uncer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = ncer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = cer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = er"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = r"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = nother-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = other-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = ther-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = her-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = er-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = r-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = -Invalid value on line 30: addons = bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = ot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = t"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = OUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = UR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = R BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = OT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = T TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = OKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = KEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = EN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = N HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = ERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = RE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = E"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = !"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Unterminated value on line 30: addons = "
#  addons = []
[jda_messages]
  enabled = true
  debug = falseUnterminated value on line 27: addons = [
    "spicord::info",
    "spicord::plugins",
    "spicord::players
    "ban_announcer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
        at com.moandjiezana.toml.Toml.read(Toml.java:74) ~[?:?]
        at org.spicord.config.SpicordConfiguration.load(SpicordConfiguration.java:85) ~[?:?]
        at org.spicord.config.SpicordConfiguration.<init>(SpicordConfiguration.java:77) ~[?:?]
        at org.spicord.SpicordLoader.<init>(SpicordLoader.java:75) ~[?:?]
        at org.spicord.SpicordLoader.<init>(SpicordLoader.java:53) ~[?:?]
        at org.spicord.bungee.SpicordBungee.onEnable(SpicordBungee.java:50) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483]
Caused by: java.lang.IllegalStateException: Invalid value on line 30: addons = ban_announcer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = an_announcer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = n_announcer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = _announcer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = announcer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = nnouncer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = nouncer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = ouncer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = uncer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = ncer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = cer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = er"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = r"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = nother-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = other-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = ther-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = her-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = er-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = r-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = -Invalid value on line 30: addons = bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = ot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = t"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = OUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = UR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = R BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = OT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = T TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = OKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = KEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = EN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = N HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = ERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = RE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = E"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Invalid value on line 30: addons = !"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
Unterminated value on line 30: addons = "
#  addons = []
[jda_messages]
  enabled = true
  debug = falseUnterminated value on line 27: addons = [
    "spicord::info",
    "spicord::plugins",
    "spicord::players
    "ban_announcer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []
[jda_messages]
  enabled = true
  debug = false
        at com.moandjiezana.toml.Toml.read(Toml.java:140) ~[?:?]
        at com.moandjiezana.toml.Toml.read(Toml.java:107) ~[?:?]
        at com.moandjiezana.toml.Toml.read(Toml.java:72) ~[?:?]
        ... 9 more
```

**Comment by anvorgesa** [comment]
You deleted the ending quote (") and didn't put a comma (,) after it
```
    "spicord::info",
    "spicord::plugins",
    "spicord::players    <--- here
    "ban_announcer"
 ```
