### ISSUE TITLE
Banannouncer not posting in discord.

### ISSUE THREAD

**Issue by SpookGezichtje** [Spicord/BanAnnouncer#94]
Hello,

Since I've updated litebans I started to get this error:
`[29.07 00:33:43] [Server] [INFO] GhostDwight issued server command: /tempmute GhostDwight 1m noob
[29.07 00:33:43] [Server] [WARN] java.sql.SQLException: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.
[29.07 00:33:43] [Server] [WARN] 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
[29.07 00:33:43] [Server] [WARN] 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[29.07 00:33:43] [Server] [WARN] 	at com.mysql.cj.jdbc.result.ResultSetImpl.first(ResultSetImpl.java:617)
[29.07 00:33:43] [Server] [WARN] 	at LiteBans.jar//litebans.bJ.first(bJ.java)
[29.07 00:33:43] [Server] [WARN] 	at BanAnnouncer_2.6.3.jar//eu.mcdb.ban_announcer.listener.LiteBansListener.getPlayerName(LiteBansListener.java:119)
[29.07 00:33:43] [Server] [WARN] 	at BanAnnouncer_2.6.3.jar//eu.mcdb.ban_announcer.listener.LiteBansListener.handleEntry(LiteBansListener.java:81)
[29.07 00:33:43] [Server] [WARN] 	at BanAnnouncer_2.6.3.jar//eu.mcdb.ban_announcer.listener.LiteBansListener$InternalListener.entryAdded(LiteBansListener.java:138)
[29.07 00:33:43] [Server] [WARN] 	at LiteBans.jar//litebans.a2.b(a2.java:13)
[29.07 00:33:43] [Server] [WARN] 	at LiteBans.jar//litebans.cA.run(cA.java:57)
[29.07 00:33:43] [Server] [WARN] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[29.07 00:33:43] [Server] [WARN] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[29.07 00:33:43] [Server] [WARN] 	at java.base/java.lang.Thread.run(Thread.java:833)
[29.07 00:33:43] [Server] [ERROR] [LiteBans] An uncaught exception was thrown by a LiteBans API event listener.
[29.07 00:33:43] [Server] [ERROR] [LiteBans] This is likely a bug in a plugin which is using the LiteBans API.
[29.07 00:33:43] [Server] [WARN] java.lang.IllegalStateException: Couldn't fetch player name from UUID '2b59fc34-65e8-3821-9836-76b34a600967'. The message was not sent.
[29.07 00:33:43] [Server] [WARN] 	at BanAnnouncer_2.6.3.jar//eu.mcdb.ban_announcer.listener.LiteBansListener.handleEntry(LiteBansListener.java:84)
[29.07 00:33:43] [Server] [WARN] 	at BanAnnouncer_2.6.3.jar//eu.mcdb.ban_announcer.listener.LiteBansListener$InternalListener.entryAdded(LiteBansListener.java:138)
[29.07 00:33:43] [Server] [WARN] 	at LiteBans.jar//litebans.a2.b(a2.java:13)
[29.07 00:33:43] [Server] [WARN] 	at LiteBans.jar//litebans.cA.run(cA.java:57)
[29.07 00:33:43] [Server] [WARN] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[29.07 00:33:43] [Server] [WARN] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[29.07 00:33:43] [Server] [WARN] 	at java.base/java.lang.Thread.run(Thread.java:833)`

This is upon every kind of litebans thing, mute kick etc.

I am running the latest version of all of them.

Litebans 2.10.3
BanAnnouncer 2.6.3
Spicord 4.2.2

Thanks for looking to this issue ticket.

**Comment by anvorgesa** [comment]
Fixed, the .jar is inside this .zip, I needed to zip it as GitHub doesn't allows to upload .jar files.
[BanAnnouncer_2.6.3.zip](https://github.com/Spicord/BanAnnouncer/files/9223897/BanAnnouncer_2.6.3.zip)
