### ISSUE TITLE
LiteBans Error -> Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.

### ISSUE THREAD

**Issue by PanetiX** [Spicord/BanAnnouncer#96]
Hey, i get this error when i warn a player with LiteBans since i install Spicord with BanAnnouncer:

[11:37:15] [LiteBans-0/ERROR]: java.sql.SQLException: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.
[11:37:15] [LiteBans-0/ERROR]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
[11:37:15] [LiteBans-0/ERROR]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[11:37:15] [LiteBans-0/ERROR]: 	at com.mysql.cj.jdbc.result.ResultSetImpl.first(ResultSetImpl.java:617)
[11:37:15] [LiteBans-0/ERROR]: 	at litebans.aC.first(aC.java)
[11:37:15] [LiteBans-0/ERROR]: 	at eu.mcdb.ban_announcer.listener.LiteBansListener.getPlayerName(LiteBansListener.java:119)
[11:37:15] [LiteBans-0/ERROR]: 	at eu.mcdb.ban_announcer.listener.LiteBansListener.handleEntry(LiteBansListener.java:81)
[11:37:15] [LiteBans-0/ERROR]: 	at eu.mcdb.ban_announcer.listener.LiteBansListener$InternalListener.entryAdded(LiteBansListener.java:138)
[11:37:15] [LiteBans-0/ERROR]: 	at litebans.j.b(j.java:13)
[11:37:15] [LiteBans-0/ERROR]: 	at litebans.B.run(B.java:57)
[11:37:15] [LiteBans-0/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:37:15] [LiteBans-0/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:37:15] [LiteBans-0/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[11:37:15] [LiteBans-0/ERROR] [LiteBans]: An uncaught exception was thrown by a LiteBans API event listener.
[11:37:15] [LiteBans-0/ERROR] [LiteBans]: This is likely a bug in a plugin which is using the LiteBans API.
[11:37:15] [LiteBans-0/ERROR]: java.lang.IllegalStateException: Couldn't fetch player name from UUID 'd80cec15-2a4d-492c-a4f7-5d2b14425605'. The message was not sent.
[11:37:15] [LiteBans-0/ERROR]: 	at eu.mcdb.ban_announcer.listener.LiteBansListener.handleEntry(LiteBansListener.java:84)
[11:37:15] [LiteBans-0/ERROR]: 	at eu.mcdb.ban_announcer.listener.LiteBansListener$InternalListener.entryAdded(LiteBansListener.java:138)
[11:37:15] [LiteBans-0/ERROR]: 	at litebans.j.b(j.java:13)
[11:37:15] [LiteBans-0/ERROR]: 	at litebans.B.run(B.java:57)
[11:37:15] [LiteBans-0/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:37:15] [LiteBans-0/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:37:15] [LiteBans-0/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by anvorgesa** [comment]
Reading issue history is not a bad idea.
https://github.com/Spicord/BanAnnouncer/issues/94#issuecomment-1200024631
